### ISSUE TITLE
cut a new release

### ISSUE THREAD

**Issue by miabbott** [ashcrow/pivot#9]
The instructions for using `pivot` in our internal docs (https://url.corp.redhat.com/redhat-coreos) instruct users to pull the `0.0.0` release, but that is missing an important change about the location of the repo, commit 4ce06e30c.

Looks like we could use a new release and updates to the instructions internally.

**Comment by ashcrow** [comment]
This should be part of the rdgo build already, but I'll still update :-)

**Comment by miabbott** [comment]
Oh of course it is part of the compose.  My mind wasn't engaged there.

A docs update would be fabulous and enough to close it out.  Thanks!

**Comment by cgwalters** [comment]
I think part of the idea is one could pivot from an existing system (e.g. Fedora Atomic Host), but it's not clear we really want to do that or support it rather than having a custom thing.

**Comment by ashcrow** [comment]
@cgwalters you're correct. If/when we make a firm decision on that we can make sure that this is being built in Fedora-land and a binary is being produced for those outside of the wide world of `rpm`.

**Comment by ashcrow** [comment]
Documentation updated
